package com.example.recyclerview2;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    List<Book> lstBook;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        lstBook = new ArrayList<>();
        lstBook.add(new Book("2666", "Roberto Bolaño", "Completed in 2003 shortly before his death, 2666 is not only Roberto Bolaño's masterpiece but also one of the finest and most important novels of the 21st century. It's an entire world unto itself, one — not unlike our own — filled with horror, neglect, depravity, brilliance, and beauty. Epic in scope and epitomizing the \"total novel,\" 2666 fuses many different genres and styles to create a singular and unforgettable work of contemporary fiction. While Bolaño's swan song marked the pinnacle of a sadly truncated literary career, his immense talent, creativity, and vision endure.", R.drawable.book_2666));
        lstBook.add(new Book("All About Love", "Bell Hooks", "We're taught to think of love as something that happens to us. It's a magical but altogether passive experience. In her deeply personal and emphatic All About Love, renowned social activist and feminist bell hooks asserts that, in fact, love is a choice we must all make and it's not nearly as abstract or elusive as many of us have come to believe. The book not only explores the role of love in our lives and the ways our culture has distorted its meaning, but guides us — with clear definitions and examples — toward a better understanding of how to cultivate it. If you've ever wondered why some relationships stand the test of time while others crumble, you should read this book.", R.drawable.book_all_about_love));
        lstBook.add(new Book("Desert Solitaire", "Edward Abbey", "No author encapsulated and celebrated the American Southwest more engagingly than iconoclast and raconteur Edward Abbey. Desert Solitaire: A Season in the Wilderness — now nearly a half-century old — is a classic of environmental writing. In this autobiographical work, Abbey chronicles his time as a park ranger and reflects on landscape, culture, politics, tourism, environmental disregard, and degradation — doing so with a unique blend of ornery charm and breathtaking description. Though set in his beloved Southwest, Desert Solitaire beautifully and brashly captures the essence of the American outdoors, replete with disdain for those who'd seek to spoil its natural wonder. ", R.drawable.book_desert_solitaire));
        lstBook.add(new Book("Disgrace", "J. M. Coetzee", "One afternoon while talking with a friend about books, I wondered how to best describe my experience of reading Disgrace, and this is what I came up with: it's like a finely crafted, very sharp knife resting gently against your skin. The uneasiness and suspense are there from the beginning, made all the more powerful by Coetzee's control and use of spare language, and you never really take a deep breath until it's all over. Set in modern South Africa, the book explores what it's like to personally confront deep prejudices. Prejudices of gender, sexuality, class, and race. Far from being a politically correct diatribe, this novel is about how we cope, how we survive as humans, and it forces the reader to reflect upon what seems at first a very twisted reality. For each of the characters in this astonishing novel, redemption is attained through what becomes the very reshaping of their souls.", R.drawable.book_disgrace));
        lstBook.add(new Book("Geek Love", "Katherine Dunn", "This is the book I recommend more than any other — I can barely hold onto a copy of it because I am always giving it away to anyone who I think needs something that will blow the top of their skull off. On one level, it is the engaging, creepy, and extraordinary story of a family of purposely designed circus freaks, as told by the hunchback albino dwarf sister. On another level, it is a story about identity and belonging: How do you define yourself in terms of your family? Your culture? Your body? Your religion? How do you know what or who you really are?", R.drawable.book_geek_love));
        lstBook.add(new Book("Gilead", "Marilynne Robinson", "Set in 1956, Marilynne Robinson's Gilead is a letter from the elderly Reverend John Ames to his very young son. Ames has lived all of his life in Gilead, Iowa, and the novel delves into the history of the area through the characters of Ames's father and grandfather — also ministers, but deeply divided on ideas such as pacifism, duty, and the abolitionist movement. And eventually, when John Ames Boughton, Ames's namesake and godson, returns to Gilead, he brings up old tensions and sets events in motion that disturb Ames's formerly peaceful last days. Gilead is one of the most beautifully written books of the new century thus far, and Robinson's incredibly insightful grappling with faith, mortality, and what constitutes a meaningful life will resonate with readers across every spectrum.", R.drawable.book_gilead));
        lstBook.add(new Book("Giovanni Room", "James Baldwin", "It would be difficult to talk about James Baldwin's Giovanni's Room and not touch on the simple fact that this slim novel, published in 1956, is mainly a love story between two men. It seems impossible to think such a thing could be published pre-Stonewall, but such is the genius of Baldwin and the way he captures the complexities of desire, love, and the tragic cost that comes from not following your heart. \"Somebody…should have told us that not many people have ever died of love. But multitudes have perished…for the lack of it.\" This emotional wonder of a book comes down to two things: love and death. And really, what else is there in life?", R.drawable.book_giovanni_room));
        lstBook.add(new Book("Handmaid Tale", " Margaret Atwood", "Atwood's classic dystopian novel of a terrifying (and terrifyingly plausible) future America has rewarded rereading like no other book; I've probably read it 30 times by now. The world of the narrator, Offred (from \"Of Fred\" — women no longer have their own names), is chilling, but she is a magnificent survivor and chronicler, and the details of everything from mundane daily life to ritualized sex and violence to her reminiscences of the time before (our contemporary reality, as seen in the '80s) are absolutely realistic. The novel is as relevant today as ever; feminist backlashes continue to wax and wane, but women's rights remain in the spotlight. And despite its scenarios of great despair, The Handmaid's Tale is ultimately a hopeful book — Offred, and others, simply cannot be human without the possibility of hope, and therein lies the strength of the resistance. All of Atwood is worth reading, but this book best exemplifies the cultural and psychological impact that a work of fiction can create.", R.drawable.book_handmaid_tale));
        lstBook.add(new Book("Infinite Jest", "David Foster Wallace", "Infinite Jest is unique; it was bred in the optimism and new frontiersmanship of the dot-com 1990s but was simultaneously an early omen of where we are today. It looks into our present beyond what were only horizons when it was written: the tensions of a global economy, the opiate of on-demand entertainment, the near-impossible pursuit of greatness in a winner-take-all society. Tennis phenoms struggle in an absurdly demanding academy and recovering addicts search for something strong enough to help them through, all while a cadre of legless Quebecois assassins search for a movie so entertaining that they plan to use it as a weapon. At turns madcap and heart-wrenching, this is the tour-de-force novel of the forces that have shaped our new millennium and will likely continue shaping it for decades to come.", R.drawable.book_infinite_jest));
        lstBook.add(new Book("Things Falling Apart", "Chinua Achebe", "Before Things Fall Apart was published in 1958, few novels existed in English that depicted African life from the African perspective. And while the book has paved the way for countless authors since, Chinua Achebe's illuminating work remains a classic of modern African literature. Drawing on the history and customs passed down to him, Achebe tells the tale Okonkwo, a strong-willed member of a late-19th-century Nigerian village. As we follow Okonkwo's story, we get a glimpse of the intricacies of village life and the complex social structures that come into play. We then see the devastating effects of European colonization on the region and on Okonkwo himself, whose rise and fall become intertwined with the changing power dynamics. Things Fall Apart is essential reading for anyone who wants a more nuanced understanding of other ways of life, of culture clashes, of what being civilized really entails.", R.drawable.book_things_fall_apart));
        lstBook.add(new Book("To Kill a Mocking Bird", "Harper Lee", "While To Kill a Mockingbird is a favorite book of pretty much everyone who has read it, it's important to remember that it continues to be subversive and challenging to the status quo. The protagonist is a young girl named Scout and except for her father, all the main characters in the book are marginalized by the power structure of their town — a structure that still exists nearly everywhere — where wealthy white men control the lives of everyone else, and even the members of that group who want to use their status for something honorable, like Scout's father Atticus, cannot win against the flattening wave of that power. Until something about that structure really changes, this book will remain required reading for every person in America.", R.drawable.book_t0_kill_a_mockingbird));
        lstBook.add(new Book("Poems", "Elizabeth Bishop", "Elizabeth Bishop's poetry is dearly loved amongst her fans but perhaps not as well-known as it should be; for one of America's towering talents of the 20th century, she is not read nearly as much as Eliot or Whitman, or even cummings. That may be in part because of her relatively slim output — this volume of all her poetic works clocks in at only 368 pages. But the care she took with her poetry is evident; every word is perfectly chosen, none wasted or missing. Her work is fiercely intelligent, poignant, surprising, plainspoken, and wrought from imagery both familiar and extraordinary. A must-read for anyone who is interested in poetry, language, or indeed literature at all, Bishop's Poems speaks deeply to what makes us human.", R.drawable.book_poems));
        lstBook.add(new Book("Never Let Me Go", "Kazuo Ishiguro", "This is the kind of book that captures you so completely you find yourself reading it at work with the book covering your keyboard, hoping no one notices but also not really caring if you get fired. It's a subtle sci-fi story about youth, freedom, and a lot of other good stuff — too much more about the plot might take something away from the magical, transformative experience of reading it. Instead, I will say that the honest way Never Let Me Go deals with love and disappointment makes it a book that anyone who ever plans to love another person should probably read immediately.", R.drawable.book_never_let_me_go));
        lstBook.add(new Book("Lolita", "Vladimir Nabokov", "Why should everyone read a book about a pedophile's obsessive and frankly gross relationship with a little girl? Because if you are a reader — a lover of words, puns, witticisms, metaphors, and allusions — Lolita is a literary masterpiece that can't be passed over in a fit of queasy morality. Humbert Humbert, the novel's unreliable narrator, knows that he's a despicable pervert and yet the reader can't help enjoying him as he surveys post-war America and little Lolita with the droll, cynical eye of a European expat adrift in a tawdry nation, and stuck irrevocably — and irredeemably — in the memory of an adolescent love affair. Please, ignore the critics: Lolita isn't a morality tale and it isn't a love story. It's an unabashed look at a deviant mind written in some of the most deft and beautiful English ever published.", R.drawable.book_lolita));
        lstBook.add(new Book("Left Hand Of Darkness", "Ursula K. Le Guin", "Not only is The Left Hand of Darkness a masterpiece of ideas, invention, and language, but it takes conventional assumptions about gender and grinds them into a fine, powdery dust. Published in 1969, the book won both the Hugo and Nebula Awards and went on to become one of the keystones of science fiction. It tells the story of an ethnologist sent to another planet, but it is Le Guin's powers of imagination that turn The Left Hand of Darkness into something truly transcendent", R.drawable.book_left_hand_of_darkness));
        lstBook.add(new Book("Phantom Tollbooth Five", "Norton Juster", "The Phantom Tollbooth is the story of Milo, a very bored boy who comes home one day to find a magical tollbooth in his room. When Milo drives his car through the tollbooth gate, he finds himself in the Lands Beyond, a country inhabited by living language in the forms of animals, magicians, royalty, mountains, seas, and cities. From Tock the Watchdog to the listless region of The Doldrums, Milo shakes off boredom as he pursues the kidnapped Princesses Rhyme and Reason and restores peace to the Lands (currently in the clutches of the warring princes, Azaz of Dictionopolis and the Mathemagician of Digitopolis, along with a pack of demons). What sets The Phantom Tollbooth apart from other wonderful swashbuckling middle-readers is that it's also about the transformative power of language: open a book (or drive through a \"tollbooth\") and even the dreariest day dissolves into the din and glory of adventure.", R.drawable.book_phantom_tollbooth));
        lstBook.add(new Book("Slaughterhouse Five", "Kurt Vonnegut", "What Kurt Vonnegut set out to do was write a book about war, and in particular the firebombing of Dresden in World War II. What he ended up doing was writing clean around it — traveling in and out of time warps, bouncing on and off the earth, sometimes setting down on the planet Tralfamadore, millions of miles away from Dresden and millions of miles away from war. What he created was a masterpiece of satire in which every crazy, clever moment, every whimsical line, no matter how deceptively light, is imbued with the sorrow and the starkness of the atrocity Vonnegut himself witnessed in that very real war.", R.drawable.book_slaughterhouse_five));
        lstBook.add(new Book("Good Man Is Hard To Find", "Flannery O'Connor", "Flannery O'Connor's first short story collection, written in 1955, will knock you off your feet. Ruthless, penetrating, and loaded with subtext, A Good Man Is Hard to Find and Other Stories was brave for its time and feels just as consequential today. Writing in the Southern Gothic tradition in a style wholly her own, O'Connor creates characters that are misguided, stunted curiosities, but she manages to capture what's human in even the most despicable of people — which makes their doomed trajectories feel all the more tragic. And despite the disturbing events that unfold, the stories are a pleasure to read — they're infused with suspense, dark humor, and some of the most evocative imagery you'll encounter in literature. All this makes for a collection that never ceases to amaze — and begs to be reread.", R.drawable.book_good_man_is_hard_to_find));
        lstBook.add(new Book("2666", "Roberto Bolaño", "Completed in 2003 shortly before his death, 2666 is not only Roberto Bolaño's masterpiece but also one of the finest and most important novels of the 21st century. It's an entire world unto itself, one — not unlike our own — filled with horror, neglect, depravity, brilliance, and beauty. Epic in scope and epitomizing the \"total novel,\" 2666 fuses many different genres and styles to create a singular and unforgettable work of contemporary fiction. While Bolaño's swan song marked the pinnacle of a sadly truncated literary career, his immense talent, creativity, and vision endure.", R.drawable.book_2666));
        lstBook.add(new Book("All About Love", "Bell Hooks", "We're taught to think of love as something that happens to us. It's a magical but altogether passive experience. In her deeply personal and emphatic All About Love, renowned social activist and feminist bell hooks asserts that, in fact, love is a choice we must all make and it's not nearly as abstract or elusive as many of us have come to believe. The book not only explores the role of love in our lives and the ways our culture has distorted its meaning, but guides us — with clear definitions and examples — toward a better understanding of how to cultivate it. If you've ever wondered why some relationships stand the test of time while others crumble, you should read this book.", R.drawable.book_all_about_love));
        lstBook.add(new Book("Desert Solitaire", "Edward Abbey", "No author encapsulated and celebrated the American Southwest more engagingly than iconoclast and raconteur Edward Abbey. Desert Solitaire: A Season in the Wilderness — now nearly a half-century old — is a classic of environmental writing. In this autobiographical work, Abbey chronicles his time as a park ranger and reflects on landscape, culture, politics, tourism, environmental disregard, and degradation — doing so with a unique blend of ornery charm and breathtaking description. Though set in his beloved Southwest, Desert Solitaire beautifully and brashly captures the essence of the American outdoors, replete with disdain for those who'd seek to spoil its natural wonder. ", R.drawable.book_desert_solitaire));
        lstBook.add(new Book("Disgrace", "J. M. Coetzee", "One afternoon while talking with a friend about books, I wondered how to best describe my experience of reading Disgrace, and this is what I came up with: it's like a finely crafted, very sharp knife resting gently against your skin. The uneasiness and suspense are there from the beginning, made all the more powerful by Coetzee's control and use of spare language, and you never really take a deep breath until it's all over. Set in modern South Africa, the book explores what it's like to personally confront deep prejudices. Prejudices of gender, sexuality, class, and race. Far from being a politically correct diatribe, this novel is about how we cope, how we survive as humans, and it forces the reader to reflect upon what seems at first a very twisted reality. For each of the characters in this astonishing novel, redemption is attained through what becomes the very reshaping of their souls.", R.drawable.book_disgrace));
        lstBook.add(new Book("Geek Love", "Katherine Dunn", "This is the book I recommend more than any other — I can barely hold onto a copy of it because I am always giving it away to anyone who I think needs something that will blow the top of their skull off. On one level, it is the engaging, creepy, and extraordinary story of a family of purposely designed circus freaks, as told by the hunchback albino dwarf sister. On another level, it is a story about identity and belonging: How do you define yourself in terms of your family? Your culture? Your body? Your religion? How do you know what or who you really are?", R.drawable.book_geek_love));
        lstBook.add(new Book("Gilead", "Marilynne Robinson", "Set in 1956, Marilynne Robinson's Gilead is a letter from the elderly Reverend John Ames to his very young son. Ames has lived all of his life in Gilead, Iowa, and the novel delves into the history of the area through the characters of Ames's father and grandfather — also ministers, but deeply divided on ideas such as pacifism, duty, and the abolitionist movement. And eventually, when John Ames Boughton, Ames's namesake and godson, returns to Gilead, he brings up old tensions and sets events in motion that disturb Ames's formerly peaceful last days. Gilead is one of the most beautifully written books of the new century thus far, and Robinson's incredibly insightful grappling with faith, mortality, and what constitutes a meaningful life will resonate with readers across every spectrum.", R.drawable.book_gilead));
        lstBook.add(new Book("Giovanni Room", "James Baldwin", "It would be difficult to talk about James Baldwin's Giovanni's Room and not touch on the simple fact that this slim novel, published in 1956, is mainly a love story between two men. It seems impossible to think such a thing could be published pre-Stonewall, but such is the genius of Baldwin and the way he captures the complexities of desire, love, and the tragic cost that comes from not following your heart. \"Somebody…should have told us that not many people have ever died of love. But multitudes have perished…for the lack of it.\" This emotional wonder of a book comes down to two things: love and death. And really, what else is there in life?", R.drawable.book_giovanni_room));
        lstBook.add(new Book("Handmaid Tale", " Margaret Atwood", "Atwood's classic dystopian novel of a terrifying (and terrifyingly plausible) future America has rewarded rereading like no other book; I've probably read it 30 times by now. The world of the narrator, Offred (from \"Of Fred\" — women no longer have their own names), is chilling, but she is a magnificent survivor and chronicler, and the details of everything from mundane daily life to ritualized sex and violence to her reminiscences of the time before (our contemporary reality, as seen in the '80s) are absolutely realistic. The novel is as relevant today as ever; feminist backlashes continue to wax and wane, but women's rights remain in the spotlight. And despite its scenarios of great despair, The Handmaid's Tale is ultimately a hopeful book — Offred, and others, simply cannot be human without the possibility of hope, and therein lies the strength of the resistance. All of Atwood is worth reading, but this book best exemplifies the cultural and psychological impact that a work of fiction can create.", R.drawable.book_handmaid_tale));
        lstBook.add(new Book("Infinite Jest", "David Foster Wallace", "Infinite Jest is unique; it was bred in the optimism and new frontiersmanship of the dot-com 1990s but was simultaneously an early omen of where we are today. It looks into our present beyond what were only horizons when it was written: the tensions of a global economy, the opiate of on-demand entertainment, the near-impossible pursuit of greatness in a winner-take-all society. Tennis phenoms struggle in an absurdly demanding academy and recovering addicts search for something strong enough to help them through, all while a cadre of legless Quebecois assassins search for a movie so entertaining that they plan to use it as a weapon. At turns madcap and heart-wrenching, this is the tour-de-force novel of the forces that have shaped our new millennium and will likely continue shaping it for decades to come.", R.drawable.book_infinite_jest));
        lstBook.add(new Book("Things Falling Apart", "Chinua Achebe", "Before Things Fall Apart was published in 1958, few novels existed in English that depicted African life from the African perspective. And while the book has paved the way for countless authors since, Chinua Achebe's illuminating work remains a classic of modern African literature. Drawing on the history and customs passed down to him, Achebe tells the tale Okonkwo, a strong-willed member of a late-19th-century Nigerian village. As we follow Okonkwo's story, we get a glimpse of the intricacies of village life and the complex social structures that come into play. We then see the devastating effects of European colonization on the region and on Okonkwo himself, whose rise and fall become intertwined with the changing power dynamics. Things Fall Apart is essential reading for anyone who wants a more nuanced understanding of other ways of life, of culture clashes, of what being civilized really entails.", R.drawable.book_things_fall_apart));
        lstBook.add(new Book("To Kill a Mocking Bird", "Harper Lee", "While To Kill a Mockingbird is a favorite book of pretty much everyone who has read it, it's important to remember that it continues to be subversive and challenging to the status quo. The protagonist is a young girl named Scout and except for her father, all the main characters in the book are marginalized by the power structure of their town — a structure that still exists nearly everywhere — where wealthy white men control the lives of everyone else, and even the members of that group who want to use their status for something honorable, like Scout's father Atticus, cannot win against the flattening wave of that power. Until something about that structure really changes, this book will remain required reading for every person in America.", R.drawable.book_t0_kill_a_mockingbird));
        lstBook.add(new Book("Poems", "Elizabeth Bishop", "Elizabeth Bishop's poetry is dearly loved amongst her fans but perhaps not as well-known as it should be; for one of America's towering talents of the 20th century, she is not read nearly as much as Eliot or Whitman, or even cummings. That may be in part because of her relatively slim output — this volume of all her poetic works clocks in at only 368 pages. But the care she took with her poetry is evident; every word is perfectly chosen, none wasted or missing. Her work is fiercely intelligent, poignant, surprising, plainspoken, and wrought from imagery both familiar and extraordinary. A must-read for anyone who is interested in poetry, language, or indeed literature at all, Bishop's Poems speaks deeply to what makes us human.", R.drawable.book_poems));
        lstBook.add(new Book("Never Let Me Go", "Kazuo Ishiguro", "This is the kind of book that captures you so completely you find yourself reading it at work with the book covering your keyboard, hoping no one notices but also not really caring if you get fired. It's a subtle sci-fi story about youth, freedom, and a lot of other good stuff — too much more about the plot might take something away from the magical, transformative experience of reading it. Instead, I will say that the honest way Never Let Me Go deals with love and disappointment makes it a book that anyone who ever plans to love another person should probably read immediately.", R.drawable.book_never_let_me_go));
        lstBook.add(new Book("Lolita", "Vladimir Nabokov", "Why should everyone read a book about a pedophile's obsessive and frankly gross relationship with a little girl? Because if you are a reader — a lover of words, puns, witticisms, metaphors, and allusions — Lolita is a literary masterpiece that can't be passed over in a fit of queasy morality. Humbert Humbert, the novel's unreliable narrator, knows that he's a despicable pervert and yet the reader can't help enjoying him as he surveys post-war America and little Lolita with the droll, cynical eye of a European expat adrift in a tawdry nation, and stuck irrevocably — and irredeemably — in the memory of an adolescent love affair. Please, ignore the critics: Lolita isn't a morality tale and it isn't a love story. It's an unabashed look at a deviant mind written in some of the most deft and beautiful English ever published.", R.drawable.book_lolita));
        lstBook.add(new Book("Left Hand Of Darkness", "Ursula K. Le Guin", "Not only is The Left Hand of Darkness a masterpiece of ideas, invention, and language, but it takes conventional assumptions about gender and grinds them into a fine, powdery dust. Published in 1969, the book won both the Hugo and Nebula Awards and went on to become one of the keystones of science fiction. It tells the story of an ethnologist sent to another planet, but it is Le Guin's powers of imagination that turn The Left Hand of Darkness into something truly transcendent", R.drawable.book_left_hand_of_darkness));
        lstBook.add(new Book("Phantom Tollbooth Five", "Norton Juster", "The Phantom Tollbooth is the story of Milo, a very bored boy who comes home one day to find a magical tollbooth in his room. When Milo drives his car through the tollbooth gate, he finds himself in the Lands Beyond, a country inhabited by living language in the forms of animals, magicians, royalty, mountains, seas, and cities. From Tock the Watchdog to the listless region of The Doldrums, Milo shakes off boredom as he pursues the kidnapped Princesses Rhyme and Reason and restores peace to the Lands (currently in the clutches of the warring princes, Azaz of Dictionopolis and the Mathemagician of Digitopolis, along with a pack of demons). What sets The Phantom Tollbooth apart from other wonderful swashbuckling middle-readers is that it's also about the transformative power of language: open a book (or drive through a \"tollbooth\") and even the dreariest day dissolves into the din and glory of adventure.", R.drawable.book_phantom_tollbooth));
        lstBook.add(new Book("Slaughterhouse Five", "Kurt Vonnegut", "What Kurt Vonnegut set out to do was write a book about war, and in particular the firebombing of Dresden in World War II. What he ended up doing was writing clean around it — traveling in and out of time warps, bouncing on and off the earth, sometimes setting down on the planet Tralfamadore, millions of miles away from Dresden and millions of miles away from war. What he created was a masterpiece of satire in which every crazy, clever moment, every whimsical line, no matter how deceptively light, is imbued with the sorrow and the starkness of the atrocity Vonnegut himself witnessed in that very real war.", R.drawable.book_slaughterhouse_five));
        lstBook.add(new Book("Good Man Is Hard To Find", "Flannery O'Connor", "Flannery O'Connor's first short story collection, written in 1955, will knock you off your feet. Ruthless, penetrating, and loaded with subtext, A Good Man Is Hard to Find and Other Stories was brave for its time and feels just as consequential today. Writing in the Southern Gothic tradition in a style wholly her own, O'Connor creates characters that are misguided, stunted curiosities, but she manages to capture what's human in even the most despicable of people — which makes their doomed trajectories feel all the more tragic. And despite the disturbing events that unfold, the stories are a pleasure to read — they're infused with suspense, dark humor, and some of the most evocative imagery you'll encounter in literature. All this makes for a collection that never ceases to amaze — and begs to be reread.", R.drawable.book_good_man_is_hard_to_find));

        RecyclerView myrv = (RecyclerView) findViewById(R.id.recyclerview_id);
        RecyclerViewAdapter myAdapter = new RecyclerViewAdapter(this, lstBook);
        myrv.setLayoutManager(new GridLayoutManager(this, 3));
        myrv.setAdapter(myAdapter);
    }
}